# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accessory < Formula
  desc ""
  homepage ""
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/masaushi/accessory/releases/download/v0.2.1/accessory_Darwin_arm64.tar.gz"
      sha256 "b2afe0fc558b2685cd0ccfe0573a68647b486d38d534afacd88e646e7f2a93ce"

      def install
        bin.install "accessory"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masaushi/accessory/releases/download/v0.2.1/accessory_Darwin_x86_64.tar.gz"
      sha256 "6ff40564a7c584fd96461ccfaef48dfb6c69578302801e2818c148fd0a2c1607"

      def install
        bin.install "accessory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masaushi/accessory/releases/download/v0.2.1/accessory_Linux_arm64.tar.gz"
      sha256 "d55287d30e6e87f32e3bbcf72dda190acadc93c3c2298fd609248eace4fa0e26"

      def install
        bin.install "accessory"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masaushi/accessory/releases/download/v0.2.1/accessory_Linux_x86_64.tar.gz"
      sha256 "6e8e2514e63a2376342b8fe1cb6a3c36327ab10ae9daf4728c1798231def41d0"

      def install
        bin.install "accessory"
      end
    end
  end
end
