# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accessory < Formula
  desc ""
  homepage ""
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masaushi/accessory/releases/download/v0.8.0/accessory_Darwin_x86_64.tar.gz"
      sha256 "e3473be16f2cc3bcf6e180679c45e772bb543d87370bccb0d0dda88c5360df9c"

      define_method(:install) do
        bin.install "accessory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/masaushi/accessory/releases/download/v0.8.0/accessory_Darwin_arm64.tar.gz"
      sha256 "c3323b3075b38337accc0e50b67f4af0d6aeca114dc3398898badecf0eddfd00"

      define_method(:install) do
        bin.install "accessory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/masaushi/accessory/releases/download/v0.8.0/accessory_Linux_x86_64.tar.gz"
      sha256 "b99ff6ef60733ccda7f61adf2a6d7ba11b2112f0dc7b7995e86de268647866dd"
      define_method(:install) do
        bin.install "accessory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masaushi/accessory/releases/download/v0.8.0/accessory_Linux_arm64.tar.gz"
      sha256 "135f3b06248a8e2f83726ecebd42e08569bab7d2efa21aab6c72427d71063c26"
      define_method(:install) do
        bin.install "accessory"
      end
    end
  end
end
