# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accessory < Formula
  desc ""
  homepage ""
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masaushi/accessory/releases/download/v0.7.0/accessory_Darwin_x86_64.tar.gz"
      sha256 "a945adb48c5983d51aaa298dacfe3267c457c82b25b40d23d7d6499ad0564000"

      def install
        bin.install "accessory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/masaushi/accessory/releases/download/v0.7.0/accessory_Darwin_arm64.tar.gz"
      sha256 "f65babae97bc50e7ca760d213fb8a454754ebf5ac5ab72b63f3738724a9ae220"

      def install
        bin.install "accessory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/masaushi/accessory/releases/download/v0.7.0/accessory_Linux_x86_64.tar.gz"
      sha256 "e56d15b18a283d55432fbf90c2dd9a45136349e36caa4855b671670c2d0a2d2b"
      def install
        bin.install "accessory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masaushi/accessory/releases/download/v0.7.0/accessory_Linux_arm64.tar.gz"
      sha256 "af261e9a9741e123926d745164ef0cdd4ae4579b80c8b3bdf170532963651c72"
      def install
        bin.install "accessory"
      end
    end
  end
end
