# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsplorer < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.3.0/ecsplorer_Darwin_x86_64.tar.gz"
      sha256 "0f522badf8779a7b479b281a4a2695d43321d4569cfb83c0d17a2d6dab990e98"

      define_method(:install) do
        bin.install "ecsplorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.3.0/ecsplorer_Darwin_arm64.tar.gz"
      sha256 "823b3d6e17be33d8047e2d2f2adac772072ff6fc532b2f5fa6433ab9315da9f0"

      define_method(:install) do
        bin.install "ecsplorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.3.0/ecsplorer_Linux_x86_64.tar.gz"
      sha256 "d5ca78412592d37e0add8f57003d861ae2359f9d7623e84ba6b5899c152be8c9"
      define_method(:install) do
        bin.install "ecsplorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.3.0/ecsplorer_Linux_arm64.tar.gz"
      sha256 "1e4c1f114d40b7c9b5b2b4e4487ae1cc56bb49b1442821cf11bcea58544ce8ed"
      define_method(:install) do
        bin.install "ecsplorer"
      end
    end
  end
end
