# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsplorer < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.1.0/ecsplorer_Darwin_x86_64.tar.gz"
      sha256 "cf3c8a5d5970a3d130cfa70301949a4d4ae9d3cb96a29204f2913b6a6a62535e"

      def install
        bin.install "ecsplorer"
      end
    end
    on_arm do
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.1.0/ecsplorer_Darwin_arm64.tar.gz"
      sha256 "392f320610172cf1bd575ca79a71769fdd5808deecd60628583e53162d1931a5"

      def install
        bin.install "ecsplorer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/masaushi/ecsplorer/releases/download/v0.1.0/ecsplorer_Linux_x86_64.tar.gz"
        sha256 "297683e07675a8c224d05585eb9a6ff38182dcd32a059ab6c0cea77aff269db7"

        def install
          bin.install "ecsplorer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/masaushi/ecsplorer/releases/download/v0.1.0/ecsplorer_Linux_arm64.tar.gz"
        sha256 "75117f74888e6a93efa843d75ecf337db3a2bb05ea14688f10b019d5c1d7dafe"

        def install
          bin.install "ecsplorer"
        end
      end
    end
  end
end
