# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsplorer < Formula
  desc ""
  homepage ""
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.0.7/ecsplorer_Darwin_x86_64.tar.gz"
      sha256 "276828c121deac008187c4cc65f7af123c25f2307291a328e351f9166c980b9c"

      def install
        bin.install "ecsplorer"
      end
    end
    on_arm do
      url "https://github.com/masaushi/ecsplorer/releases/download/v0.0.7/ecsplorer_Darwin_arm64.tar.gz"
      sha256 "ca5ce5ff0ac9ec3924fa264affb5fa17eeec2da1241ce2e30a5ad7d539026104"

      def install
        bin.install "ecsplorer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/masaushi/ecsplorer/releases/download/v0.0.7/ecsplorer_Linux_x86_64.tar.gz"
        sha256 "32fffe3b2c14e8a4d498e2a02d89c7350dc50cdd5b91acbb8f3ec124ea32c0fe"

        def install
          bin.install "ecsplorer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/masaushi/ecsplorer/releases/download/v0.0.7/ecsplorer_Linux_arm64.tar.gz"
        sha256 "8ec708d079290f4bfe19ed2ed847d0027417c9bed982500926d7b1717bfe6fff"

        def install
          bin.install "ecsplorer"
        end
      end
    end
  end
end
